import { z } from "zod";

const schema = z.object({
  NEXT_PUBLIC_BRAND_NAME: z.string().default("Noxis"),
  NEXT_PUBLIC_BRAND_TAGLINE: z.string().default("Descubre qué IA gana para ti"),
  NEXT_PUBLIC_SITE_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_SUPPORT_EMAIL: z.string().email().default("soporte@example.com"),
  NEXT_PUBLIC_CONTACT_EMAIL: z.string().email().default("hola@example.com"),
  NEXT_PUBLIC_PARTNERSHIPS_EMAIL: z.string().email().default("alianzas@example.com"),
  NEXT_PUBLIC_SUPABASE_URL: z.string().optional(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  SUPABASE_JWT_SECRET: z.string().optional(),
  NEXT_PUBLIC_SOCIAL_X_URL: z.preprocess((v) => v === "" ? undefined : v, z.string().url().optional()),
  NEXT_PUBLIC_SOCIAL_LINKEDIN_URL: z.preprocess((v) => v === "" ? undefined : v, z.string().url().optional()),
  NEXT_PUBLIC_SOCIAL_INSTAGRAM_URL: z.preprocess((v) => v === "" ? undefined : v, z.string().url().optional()),
  NEXT_PUBLIC_SOCIAL_YOUTUBE_URL: z.preprocess((v) => v === "" ? undefined : v, z.string().url().optional()),
  MAILERLITE_API_KEY: z.string().optional(),
  MAILERLITE_GROUP_ID: z.string().optional(),
  MAILERLITE_WEBHOOK_SECRET: z.string().optional(),
  NEXT_PUBLIC_GA_ID: z.string().optional(),
  NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
  NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
  NEXT_PUBLIC_ADSENSE_CLIENT: z.preprocess((v) => v === "" ? undefined : v, z.string().optional()),
  NEXT_PUBLIC_ADSENSE_SLOT_BLOG: z.preprocess((v) => v === "" ? undefined : v, z.string().optional()),
  NEXT_PUBLIC_ADSENSE_SLOT_NEWS: z.preprocess((v) => v === "" ? undefined : v, z.string().optional()),
  OPENAI_API_KEY: z.preprocess((v) => v === "" ? undefined : v, z.string().optional()),
  OPENAI_FORUM_MODEL: z.preprocess((v) => v === "" ? undefined : v, z.string().optional()),
  FORUM_CRON_SECRET: z.preprocess((v) => v === "" ? undefined : v, z.string().optional()),
  CRON_SECRET: z.preprocess((v) => v === "" ? undefined : v, z.string().optional()),
});

export const env = schema.parse({
  NEXT_PUBLIC_BRAND_NAME: process.env.NEXT_PUBLIC_BRAND_NAME,
  NEXT_PUBLIC_BRAND_TAGLINE: process.env.NEXT_PUBLIC_BRAND_TAGLINE,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_SUPPORT_EMAIL: process.env.NEXT_PUBLIC_SUPPORT_EMAIL,
  NEXT_PUBLIC_CONTACT_EMAIL: process.env.NEXT_PUBLIC_CONTACT_EMAIL,
  NEXT_PUBLIC_PARTNERSHIPS_EMAIL: process.env.NEXT_PUBLIC_PARTNERSHIPS_EMAIL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_JWT_SECRET: process.env.SUPABASE_JWT_SECRET,
  NEXT_PUBLIC_SOCIAL_X_URL: process.env.NEXT_PUBLIC_SOCIAL_X_URL,
  NEXT_PUBLIC_SOCIAL_LINKEDIN_URL: process.env.NEXT_PUBLIC_SOCIAL_LINKEDIN_URL,
  NEXT_PUBLIC_SOCIAL_INSTAGRAM_URL: process.env.NEXT_PUBLIC_SOCIAL_INSTAGRAM_URL,
  NEXT_PUBLIC_SOCIAL_YOUTUBE_URL: process.env.NEXT_PUBLIC_SOCIAL_YOUTUBE_URL,
  MAILERLITE_API_KEY: process.env.MAILERLITE_API_KEY,
  MAILERLITE_GROUP_ID: process.env.MAILERLITE_GROUP_ID,
  MAILERLITE_WEBHOOK_SECRET: process.env.MAILERLITE_WEBHOOK_SECRET,
  NEXT_PUBLIC_GA_ID: process.env.NEXT_PUBLIC_GA_ID,
  NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
  NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
  NEXT_PUBLIC_ADSENSE_CLIENT: process.env.NEXT_PUBLIC_ADSENSE_CLIENT,
  NEXT_PUBLIC_ADSENSE_SLOT_BLOG: process.env.NEXT_PUBLIC_ADSENSE_SLOT_BLOG,
  NEXT_PUBLIC_ADSENSE_SLOT_NEWS: process.env.NEXT_PUBLIC_ADSENSE_SLOT_NEWS,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_FORUM_MODEL: process.env.OPENAI_FORUM_MODEL,
  FORUM_CRON_SECRET: process.env.FORUM_CRON_SECRET,
  CRON_SECRET: process.env.CRON_SECRET,
});
